name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 192.144.154.17
        username: root
        port: 52631
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          if [ -d "/www/wwwroot/August/.git" ]; then
            cd /www/wwwroot/August
            git pull
          else
            mkdir -p /www/wwwroot
            cd /www/wwwroot
            mkdir -p /root/.ssh
            ssh-keyscan github.com >> /root/.ssh/known_hosts
            git clone git@github.com:qianqiuyueying/august-lab.git August
            cd /www/wwwroot/August
          fi
          ./scripts/deploy.sh
